### PR TITLE
remove ignore lifecycle owing to terraform aws provider fix

### PR DESCRIPTION
**Pull request by jvisker**
Terraform issue: https://github.com/terraform-providers/terraform-provider-aws/issues/7128
Terraform pr fix: https://github.com/terraform-providers/terraform-provider-aws/pull/11885

### CODE REVIEW

**Review by yoshutch — CHANGES_REQUESTED** [review]
don't forget to change the example in the README to have the latest version

do we need to put in the README that this requires aws provider version 2.56 or greater?

**Comment by jvisker** [comment]
@yoshutch I did change the readme example version. And I don't think we need to specify the required version in the documentation. We didn't do it before and I think terraform makes it fairly clear when you try to run commands that you need to do another init.

**Review by yoshutch — APPROVED** [review]
😅 yes you did. my bad. lgtm

**Comment by jvisker** [comment]
Also, I did test the changes. Now the termination wait time can actually be changed.

**Pull request merged**
